[2024-05-16T18:01:31.790Z] info: docker.yaml was copied to the config folder
[2024-05-16T18:01:31.794Z] info: services.yaml was copied to the config folder
[2024-05-16T18:01:31.795Z] info: bookmarks.yaml was copied to the config folder
[2024-05-16T18:01:31.796Z] info: widgets.yaml was copied to the config folder
[2024-05-16T18:01:31.796Z] info: custom.css was copied to the config folder
[2024-05-16T18:01:31.797Z] info: custom.js was copied to the config folder
[2024-05-16T18:01:31.837Z] info: kubernetes.yaml was copied to the config folder
[2024-05-16T19:53:30.180Z] error: <httpProxy> Error calling http://pm.pansiere.com/...
[2024-05-16T19:53:30.184Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:95:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:326:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:483:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:91:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-05-16T19:53:30.291Z] error: <httpProxy> Error calling http://pm.pansiere.com/...
[2024-05-16T19:53:30.292Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:95:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:326:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:483:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:91:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-05-16T20:02:31.451Z] error: <httpProxy> Error calling https://pi-hole.pansiere.cc/...
[2024-05-16T20:02:31.456Z] error: <httpProxy> [
  500,
  Error: write EPROTO D8895C14D3790000:error:0A000458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590:SSL alert number 112
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-05-16T20:02:31.482Z] error: <httpProxy> Error calling https://pi-hole.pansiere.cc/...
[2024-05-16T20:02:31.483Z] error: <httpProxy> [
  500,
  Error: write EPROTO D8895C14D3790000:error:0A000458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590:SSL alert number 112
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-05-16T20:02:31.699Z] error: <httpProxy> Error calling https://pi-hole.pansiere.cc/...
[2024-05-16T20:02:31.700Z] error: <httpProxy> [
  500,
  Error: write EPROTO D8895C14D3790000:error:0A000458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590:SSL alert number 112
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-05-16T20:02:31.708Z] error: <httpProxy> Error calling https://pi-hole.pansiere.cc/...
[2024-05-16T20:02:31.709Z] error: <httpProxy> [
  500,
  Error: write EPROTO D8895C14D3790000:error:0A000458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590:SSL alert number 112
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-05-16T20:02:34.539Z] error: <httpProxy> Error calling https://pi-hole.pansiere.cc/...
[2024-05-16T20:02:34.540Z] error: <httpProxy> [
  500,
  Error: write EPROTO D8895C14D3790000:error:0A000458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590:SSL alert number 112
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-05-16T20:02:34.544Z] error: <httpProxy> Error calling https://pi-hole.pansiere.cc/...
[2024-05-16T20:02:34.545Z] error: <httpProxy> [
  500,
  Error: write EPROTO D8895C14D3790000:error:0A000458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590:SSL alert number 112
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-06-25T00:26:29.812Z] error: <httpProxy> Error calling https://wazuh.pansiere.com/...
[2024-06-25T00:26:29.825Z] error: <httpProxy> [
  500,
  AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1173:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1632:3)
      at listOnTimeout (node:internal/timers:571:11)
      at process.processTimers (node:internal/timers:512:7) {
    code: 'ENETUNREACH',
    [errors]: [ [Error], [Error] ]
  }
]
[2024-06-25T00:26:34.092Z] error: <httpProxy> Error calling https://wazuh.pansiere.com/...
[2024-06-25T00:26:34.093Z] error: <httpProxy> [
  500,
  AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1173:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1632:3)
      at listOnTimeout (node:internal/timers:571:11)
      at process.processTimers (node:internal/timers:512:7) {
    code: 'ENETUNREACH',
    [errors]: [ [Error], [Error] ]
  }
]
[2024-06-30T21:17:40.297Z] error: <httpProxy> Error calling https://pm.pansiere.com/...
[2024-06-30T21:17:40.301Z] error: <httpProxy> [
  500,
  AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1173:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1632:3)
      at listOnTimeout (node:internal/timers:571:11)
      at process.processTimers (node:internal/timers:512:7) {
    code: 'ENETUNREACH',
    [errors]: [ [Error], [Error] ]
  }
]
